import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      // The TOON client dynamically imports these to settle on Mina, which
      // this app never does. Left unaliased they add ~15 MB to the bundle.
      // See `src/shared/api/minaUnavailable.ts`.
      o1js: path.resolve(__dirname, "src/shared/api/minaUnavailable.ts"),
      "mina-signer": path.resolve(
        __dirname,
        "src/shared/api/minaUnavailable.ts",
      ),
      // @toon-protocol/rig's factory-job delivery port calls Node's
      // `crypto.createHash` directly (no browser build). Left unaliased,
      // Vite externalizes the bare `crypto` specifier to an empty stub —
      // see `src/shared/api/nodeCryptoBrowserShim.ts` for exactly which
      // call shape this covers.
      crypto: path.resolve(
        __dirname,
        "src/shared/api/nodeCryptoBrowserShim.ts",
      ),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
